spring.application.name=userapi

## Application port
server.port=8080

## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/dev
spring.datasource.username=postgres
spring.datasource.password=123456

# Driver e Dialeto (opcionais em versões recentes, mas recomendados)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Estratégia de criação de tabelas
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

## Default Schema
spring.flyway.schemas=users
spring.jpa.hibernate.default_schema=users